#!/bin/bash
set -e -u
set -o pipefail

# Given an MKV file generated by the SDK:
# 1. The Cluster is always followed by Tags
# 2. The Cluster comes first
# 3. Tag group (containing "AWS_KINESISVIDEO_END_OF_FRAGMENT") has at least 2 tags.
#
# Otherwise, given an MKV file returned from KVS service:
# 1. There are 2 Tag groups
# 2. The service metadata tags come before the cluster
# 3. The user metadata tags come after the cluster
#
# Usage: ./validate-mkv-containing-tags.sh <MKV filePath>
#  - Must have mkvinfo (mkvtoolnix) installed

set -e

file="$1"

if [[ ! -f "$file" ]]; then
    echo "$file not found!"
    exit 1
fi

clusters=0                   # Count of clusters in the MKV
tags=0                       # Count of user tag groups in the MKV
last_was_tag=0               # If the previous element is a tag (used to de-duplicate tag groups)
last_tag_group_size=0        # Number of tags in the final tag group in the MKV
first_element=""             # Either cluster, or non-service metadata tag group
last_element=""              # Either cluster, or tag, whichever comes last in the MKV
inside_last_tag_group=0      # If the last group has "AWS_KINESISVIDEO_END_OF_FRAGMENT"
aws_only_tag_group=0         # If the current tag group only has tag keys starting with 'AWS_' (e.g. AWS_KINESISVIDEO_FRAGMENT_NUMBER)
valid_tag_group_found=0      # If there is at least 1 user metadata tags tag group
non_user_metadata_cluster=0  # If there is a tag group containing all 'AWS_'-prefixed keys

echo "### MKV Structure Validation for $file 🚀"

while IFS= read -r line; do
    if [[ -z "$first_element" && ("$line" =~ "+ Cluster" || "$line" =~ "+ Tags") ]]; then
        first_element="$line"
    fi

    if [[ "$line" =~ "|+" ]]; then
        last_element="$line"
    fi

    if [[ "$line" =~ "|+ Cluster" ]]; then
        if [[ "$aws_only_tag_group" -eq 1 ]]; then
          ((tags--))
        fi

        ((clusters++))
        last_was_tag=0
        inside_last_tag_group=0
    elif [[ "$line" =~ "+ Tags" ]]; then
        if [[ $last_was_tag -eq 0 ]]; then
            ((tags++))
            last_tag_group_size=1
            aws_only_tag_group=1
        else
            ((last_tag_group_size++))
        fi
        last_was_tag=1

    elif [[ "$line" =~ "AWS_KINESISVIDEO_END_OF_FRAGMENT" ]]; then
        inside_last_tag_group=1

    elif [[ "$line" =~ "|   + Name" ]]; then
        if [[ ! "$line" =~ "AWS_" ]]; then
            aws_only_tag_group=0
        else
            non_user_metadata_cluster=1
            first_element=""
        fi

    elif [[ ! "$line" =~ "+ Tag" && ! "$line" =~ "+ Simple" && ! "$line" =~ "+ Name" && ! "$line" =~ "+ String" ]]; then
        last_was_tag=0
    fi

    if [[ $aws_only_tag_group -eq 0 ]]; then
        valid_tag_group_found=1
    fi
done < <(mkvinfo -v "$file" 2>/dev/null)

if [[ non_user_metadata_cluster -eq 1 ]]; then
  echo "**MKV type:** persisted MKV"
else
  echo "**MKV type:** SDK-generated MKV"
fi

echo "**Clusters Found:** $clusters"
echo "**Tags Found:** $tags"

error=0

if [[ "$first_element" =~ "Tags" ]]; then
    echo "❌ Error: Tags appear before any Cluster!"
    echo "$first_element"
    error=1
else
    echo "✅ Tags appear after Clusters (OK)"
fi

if [[ ! "$last_element" =~ "Tags" ]]; then
    echo "❌ Error: Last section is not Tags!"
    error=1
else
    echo "✅ Last section is Tags (OK)"
fi

if [[ $clusters -eq 0 ]]; then
    echo "❌ Error: No Clusters found! Invalid MKV structure?"
    error=1
else
    echo "✅ Clusters detected (OK)"
fi

if [[ $tags -gt $clusters ]]; then
    echo "❌️ Warning: More tags than clusters."
fi

# Last tag group only contains AWS_KINESISVIDEO_END_OF_FRAGMENT
if [[ $inside_last_tag_group -eq 1 && $last_tag_group_size -le 1 && $aws_only_tag_group -eq 1 ]]; then
    echo "❌ Error: Last tag group (containing AWS_KINESISVIDEO_END_OF_FRAGMENT) doesn't have any user metadata!"
    error=1
else
    echo "$inside_last_tag_group $last_tag_group_size $aws_only_tag_group"
    echo "✅ Last tag group has at last one non-AWS_KINESISVIDEO_END_OF_FRAGMENT tag (OK)"
fi

if [[ $valid_tag_group_found -eq 0 ]]; then
    echo "❌ Error: No user metadata tags found! All the tag keys start with 'AWS_'"
    error=1
else
    echo "✅ Located user metadata tags."
fi

if [[ $error -ne 0 ]]; then
  echo "#### ❌ MKV validation failed for $file"
  echo "\`\`\`"
  mkvinfo -v "$file"
  echo "\`\`\`"
fi
exit $error